spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://host:5432/database"
    username: "username"
    password: "password"

application:
  version: ${version}

discord:
  token: "Bot Token"
  owner: Bot Owner ID
  bot: Bot ID
  guild: Guild ID (For testing slash commands)
