discord:
  token: token
  ownerId: id
  guildId: id

spring:
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host:5432/database
    username: username
    password: password
