spring:
    datasource:
        driver-class-name: "org.postgresql.Driver"
        url: "jdbc:postgresql://localhost:5432/database"
        username: "username"
        password: "password"

discord:
    token: "token"
    owner: "owner"
