discord:
  token: token
  ownerId: owner id
  guildId: guild id

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host:5432/database
    username: username
    password: password
